export type LegacySeedCatalogKey = {
  type: "fermentable" | "hop" | "yeast" | "sugar" | "adjunct" | "fining" | "misc";
  normalizedName: string;
};

export const legacyDevSeedCatalogKeys: LegacySeedCatalogKey[] = [
  { type: "fermentable", normalizedName: "pilsner malt" },
  { type: "fermentable", normalizedName: "pale ale malt" },
  { type: "fermentable", normalizedName: "wheat malt" },
  { type: "fermentable", normalizedName: "munich malt" },
  { type: "fermentable", normalizedName: "vienna malt" },
  { type: "fermentable", normalizedName: "maris otter pale malt" },
  { type: "fermentable", normalizedName: "caramunich i" },
  { type: "fermentable", normalizedName: "crystal 60l" },
  { type: "fermentable", normalizedName: "chocolate malt" },
  { type: "fermentable", normalizedName: "roasted barley" },
  { type: "hop", normalizedName: "citra" },
  { type: "hop", normalizedName: "mosaic" },
  { type: "hop", normalizedName: "saaz" },
  { type: "hop", normalizedName: "cascade" },
  { type: "hop", normalizedName: "centennial" },
  { type: "hop", normalizedName: "simcoe" },
  { type: "hop", normalizedName: "amarillo" },
  { type: "hop", normalizedName: "magnum" },
  { type: "hop", normalizedName: "hallertau mittelfruh" },
  { type: "hop", normalizedName: "nelson sauvin" },
  { type: "yeast", normalizedName: "safale us-05" },
  { type: "yeast", normalizedName: "mangrove jacks m21 belgian wit" },
  { type: "yeast", normalizedName: "lalbrew voss kveik" },
  { type: "yeast", normalizedName: "saflager w-34-70" },
  { type: "yeast", normalizedName: "lalbrew verdant ipa" },
  { type: "yeast", normalizedName: "lallemand nottingham ale" },
  { type: "yeast", normalizedName: "belle saison" },
  { type: "yeast", normalizedName: "wyeast 1056 american ale" },
  { type: "yeast", normalizedName: "white labs wlp001 california ale" },
  { type: "yeast", normalizedName: "safale k-97" },
  { type: "sugar", normalizedName: "dextrose" },
  { type: "sugar", normalizedName: "sucrose" },
  { type: "sugar", normalizedName: "lactose" },
  { type: "sugar", normalizedName: "maltodextrin" },
  { type: "sugar", normalizedName: "candi sugar clear" },
  { type: "sugar", normalizedName: "candi syrup d-45" },
  { type: "sugar", normalizedName: "turbinado sugar" },
  { type: "sugar", normalizedName: "honey" },
  { type: "sugar", normalizedName: "maple syrup" },
  { type: "sugar", normalizedName: "molasses" },
  { type: "adjunct", normalizedName: "flaked oats" },
  { type: "adjunct", normalizedName: "flaked barley" },
  { type: "adjunct", normalizedName: "flaked wheat" },
  { type: "adjunct", normalizedName: "flaked rye" },
  { type: "adjunct", normalizedName: "flaked maize" },
  { type: "adjunct", normalizedName: "rice hulls" },
  { type: "adjunct", normalizedName: "torrified wheat" },
  { type: "adjunct", normalizedName: "cocoa nibs" },
  { type: "adjunct", normalizedName: "peanut butter powder" },
  { type: "adjunct", normalizedName: "coconut flakes" },
  { type: "fining", normalizedName: "irish moss" },
  { type: "fining", normalizedName: "whirlfloc" },
  { type: "fining", normalizedName: "gelatin" },
  { type: "fining", normalizedName: "biofine clear" },
  { type: "fining", normalizedName: "isinglass" },
  { type: "fining", normalizedName: "super moss" },
  { type: "fining", normalizedName: "kieselsol" },
  { type: "fining", normalizedName: "chitosan" },
  { type: "fining", normalizedName: "pvpp" },
  { type: "fining", normalizedName: "sparkolloid" },
  { type: "misc", normalizedName: "yeast nutrient" },
  { type: "misc", normalizedName: "servomyces" },
  { type: "misc", normalizedName: "campden tablet" },
  { type: "misc", normalizedName: "gypsum" },
  { type: "misc", normalizedName: "calcium chloride" },
  { type: "misc", normalizedName: "epsom salt" },
  { type: "misc", normalizedName: "lactic acid 88" },
  { type: "misc", normalizedName: "phosphoric acid 10" },
  { type: "misc", normalizedName: "potassium metabisulfite" },
  { type: "misc", normalizedName: "star san" }
];
